name: JS tests master

on:
  push:
    branches:
      - master
      - 3.x-maintenance
    paths:
      - '.github/scripts/*.sh'
      - '.github/workflows/*.yml'
      - 'gui/package.json'
      - 'requirements/*.txt'
      - 'Makefile'
      - 'MANIFEST.in'
      - '**.bat'
      - '**.jsx?'
      - '**.sh'

  pull_request:
    branches:
      - master
      - 3.x-maintenance
    paths:
      - '.github/scripts/*.sh'
      - '.github/workflows/*.yml'
      - 'gui/package.json'
      - 'requirements/*.txt'
      - 'MANIFEST.in'
      - '**.bat'
      - '**.jsx?'
      - '**.sh'

jobs:
  ############################################################################
  # Close previous builds on the same branch
  ############################################################################
  cleanup-previous-runs:
    name: Cleanup previous builds
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  ############################################################################
  # Lint jobs
  ############################################################################
  lint-js:
    name: Lint JS
    needs: cleanup-previous-runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch branches
        run: git fetch --prune --unshallow
      - name: Check build skips
        shell: bash -l {0}
        run: source .github/scripts/check_skip.sh
      - name: Cache node
        if: env.RUN_BUILD == 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-13-${{ hashFiles('**/lektor/admin/package-lock.json') }}
      - name: Setup node
        if: env.RUN_BUILD == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Install node dependencies
        if: env.RUN_BUILD == 'true'
        run: |
          cd lektor/admin/
          npm install .
          npm run webpack
      - name: Show node environment
        if: env.RUN_BUILD == 'true'
        run: |
          node --version
          npm --version
      - name: Run JS lint
        if: env.RUN_BUILD == 'true'
        run: |
          cd lektor/admin/
          npm run lint

  ############################################################################
  # Smoke tests
  ############################################################################
  linux-smoke-node:
    name: Linux node${{ matrix.NODEJS_VERSION }} smoke test
    needs: cleanup-previous-runs
    runs-on: ubuntu-latest
    env:
      CI: True
      NODEJS_VERSION: ${{ matrix.NODEJS_VERSION }}
    strategy:
      fail-fast: false 
      matrix:
        NODEJS_VERSION: ['13']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch branches
        run: git fetch --prune --unshallow
      - name: Check build skips
        shell: bash -l {0}
        run: source .github/scripts/check_skip.sh
      - name: Cache node
        if: env.RUN_BUILD == 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.NODEJS_VERSION }}-${{ hashFiles('**/lektor/admin/package-lock.json') }}
      - name: Setup node
        if: env.RUN_BUILD == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.NODEJS_VERSION }}
      - name: Install node dependencies
        if: env.RUN_BUILD == 'true'
        run: |
          cd lektor/admin/
          npm install .
          npm run webpack
      - name: Show node environment
        if: env.RUN_BUILD == 'true'
        run: |
          node --version
          npm --version

  ############################################################################
  # Node tests
  ############################################################################
  linux-node:
    name: Linux node${{ matrix.NODEJS_VERSION }} tests
    runs-on: ubuntu-latest
    needs: linux-smoke-node
    env:
      CI: True
      NODEJS_VERSION: ${{ matrix.NODEJS_VERSION }}
    strategy:
      fail-fast: false 
      matrix:
        NODEJS_VERSION: ['10', '12']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch branches
        run: git fetch --prune --unshallow
      - name: Check build skips
        shell: bash -l {0}
        run: source .github/scripts/check_skip.sh
      - name: Cache node
        if: env.RUN_BUILD == 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.NODEJS_VERSION }}-${{ hashFiles('**/lektor/admin/package-lock.json') }}
      - name: Setup node
        if: env.RUN_BUILD == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.NODEJS_VERSION }}
      - name: Install node dependencies
        if: env.RUN_BUILD == 'true'
        run: |
          cd lektor/admin/
          npm install .
          npm run webpack
      - name: Show node environment
        if: env.RUN_BUILD == 'true'
        run: |
          node --version
          npm --version

  mac-node:
    name: Mac node${{ matrix.NODEJS_VERSION }} tests
    runs-on: macos-latest
    needs: linux-smoke-node
    env:
      CI: True
      NODEJS_VERSION: ${{ matrix.NODEJS_VERSION }}
    strategy:
      fail-fast: false 
      matrix:
        NODEJS_VERSION: ['13']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch branches
        run: git fetch --prune --unshallow
      - name: Check build skips
        shell: bash -l {0}
        run: source .github/scripts/check_skip.sh
      - name: Cache node
        if: env.RUN_BUILD == 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.NODEJS_VERSION }}-${{ hashFiles('**/lektor/admin/package-lock.json') }}
      - name: Setup node
        if: env.RUN_BUILD == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.NODEJS_VERSION }}
      - name: Install node dependencies
        if: env.RUN_BUILD == 'true'
        run: |
          cd lektor/admin/
          npm install .
          npm run webpack
      - name: Show node environment
        if: env.RUN_BUILD == 'true'
        run: |
          node --version
          npm --version

  win-node:
    name: Win node${{ matrix.NODEJS_VERSION }} tests
    runs-on: windows-latest
    needs: linux-smoke-node
    env:
      CI: True
      NODEJS_VERSION: ${{ matrix.NODEJS_VERSION }}
    strategy:
      fail-fast: false 
      matrix:
        NODEJS_VERSION: ['13']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch branches
        run: git fetch --prune --unshallow
      - name: Check build skips
        shell: bash -l {0}
        run: source .github/scripts/check_skip.sh
      - name: Cache node
        if: env.RUN_BUILD == 'true'
        uses: actions/cache@v1
        with:
          path: ~\AppData\Roaming\npm-cache
          key: ${{ runner.os }}-node-${{ matrix.NODEJS_VERSION }}-${{ hashFiles('**\lektor\admin\package-lock.json') }}
      - name: Setup node
        if: env.RUN_BUILD == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.NODEJS_VERSION }}
      - name: Install node dependencies
        if: env.RUN_BUILD == 'true'
        run: |
          cd lektor/admin/
          npm install .
          npm run webpack
      - name: Show node environment
        if: env.RUN_BUILD == 'true'
        run: |
          node --version
          npm --version
